---
vpr_head: uncertainty
use_cpu: true
dataset_name: DATASET
evaluation_folder: EVALUATION_FOLDER
resume_checkpoint: MODEL_PATH/checkpoint.pth.tar
results_folder: RESULTS_FOLDER
backbone_model: mobilenetv3
seed: 123
evaluation_subsampling_rate: 10